export const data = [
  {
    completed: true,
    heading: "Design Earn's Talent Leaderboard",
    headImg: "/image1.png",
    author: "Superteam",
    date: "04/04/2023",
    credits: 700,
    placement: "1st Place",
    category: ["Design"],
    participants: 36,
  },
  {
    completed: true,
    heading: "Armada UI/UX Review",
    headImg: "/image2.png",
    author: "Dean's List Dao",
    date: "21/03/2023",
    credits: 0,
    placement: "",
    category: ["Design"],
    participants: 7,
  },
  {
    completed: true,
    heading: "Create a Frame for Farcaster",
    headImg: "/image3.png",
    author: "Deribet",
    date: "14/03/2023",
    credits: 500,
    placement: "1st Place",
    category: ["Frontend", "Backend", "Blockchain"],
    participants: 20,
  },
  {
    completed: true,
    heading: "Write a thread with memes for PP Program on Solana",
    headImg: "/image4.png",
    author: "pSTAKE Finance",
    date: "06/03/2023",
    credits: 100,
    placement: "3rd Place",
    category: ["Content"],
    participants: 12,
  },
  {
    completed: false,
    heading: "Write a thread with memes for PP Program on Solana",
    headImg: "/image4.png",
    author: "pSTAKE Finance",
    date: "06/03/2023",
    credits: 0,
    placement: "",
    category: ["Content"],
    participants: 12,
  },
  {
    completed: false,
    heading: "Armada UI/UX Review",
    headImg: "/image2.png",
    author: "Dean's List Dao",
    date: "21/03/2023",
    credits: 0,
    placement: "",
    category: ["Design"],
    participants: 7,
  },
  {
    completed: false,
    heading: "Design Earn's Talent Leaderboard",
    headImg: "/image1.png",
    author: "Superteam",
    date: "04/04/2023",
    credits: 0,
    placement: "",
    category: ["Design"],
    participants: 36,
  },
  {
    completed: false,
    heading: "Create a Frame for Farcaster",
    headImg: "/image3.png",
    author: "Deribet",
    date: "14/03/2023",
    credits: 0,
    placement: "",
    category: ["Frontend", "Backend", "Blockchain"],
    participants: 20,
  },
];
